version: "3.8"

services:
  app:
    build: .
    image: amg_surabaya-app:latest
    container_name: amg-surabaya-app
    restart: unless-stopped

    ports:
      - "8080:80"

    depends_on:
      - db

    volumes:
      - laravel_storage:/var/www/storage
      - laravel_uploads:/var/www/storage/app/public

  scheduler:
    build: .
    image: amg_surabaya-scheduler:latest
    container_name: amg-scheduler
    restart: unless-stopped
    command: php artisan schedule:work

    depends_on:
      - db

    volumes:
      - laravel_storage:/var/www/storage
      - laravel_uploads:/var/www/storage/app/public

  db:
    image: mysql:8.0

    restart: unless-stopped

    environment:
      TZ: Asia/Jakarta
      MYSQL_DATABASE: amg_owners
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: amguser
      MYSQL_PASSWORD: amgpassword

    ports:
      - "3306:3306"

    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
  laravel_storage:
  laravel_uploads:
